
GET http://localhost:3000/sites

###
POST http://localhost:3000/sites
Content-Type: application/json

{
    "name": "shsosho",
    "description": "Paris is the capital and most populous city of France, with an estimated population of 2,175,601 residents as of 2018, in an area of more than 105 square kilometres. Since the 17th century, Paris has been one of Europe's major centres of finance, diplomacy, commerce, fashion, gastronomy, science, and arts. The City of Paris is the centre and seat of government of the region and province of Île-de-France, or Paris Region, which has an estimated population of 12,174,880, or about 18 percent of the population of France as of 2017. The Paris Region had a GDP of €709 billion in 2017. According to the Economist Intelligence Unit Worldwide Cost of Living Survey in 2018, Paris was the second most expensive city in the world, after Singapore and ahead of Zürich, Hong Kong, Oslo, and Geneva. Another source ranked Paris as most expensive, on par with Singapore and Hong Kong, in 2018.",
    "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg/413px-La_Tour_Eiffel_vue_de_la_Tour_Saint-Jacques%2C_Paris_ao%C3%BBt_2014_%282%29.jpg",
    "backgroundImageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Notre_Dame_de_Paris%2C_August_2010.jpg/1280px-Notre_Dame_de_Paris%2C_August_2010.jpg"	
}

###

DELETE http://localhost:3000/sites/61c364a6e4f8f74a2f8d2573


### 

PATCH http://localhost:3000/sites/61c48bf5326e522886d15108
Content-Type: application/json

{
    "name": "mase",
    "description": "ye",
    "imageURL": "se",
    "backgroundImageURL": "se"
}

###

DELETE  http://localhost:3000/sites

###
GET http://localhost:3000/sites/Vienna
